# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 051bc738bd5e1ad61dc96a28d8bd5da335878559ab17603f101756e06a951558353ece0e7d66df8e633dbb4c792155c9fc5b3736c93c2d57e03f513c5c508bc7
  GOOGLE_KEY: '688090261241-kllc2v7q8ptn376d92tk84880efvn01f.apps.googleusercontent.com'
  GOOGLE_SECRET: '3YB7kMyhTvETatJCq-_djxGa'

test:
  secret_key_base: 5291d55a185709aaaa4256491fd3ef12a01967adc556e8659cbb0098e14c8c79769925d5037746db78cc9d42b6cd1fe80280ee25876547a31ed6399feff7bf0b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
